#import <UIKit/UIKit.h>
#include <Foundation/Foundation.h>
#include <objc/runtime.h>

@interface FirstViewController:NSObject{
@protected
	NSMutableArray *newAppsList;
	UITableView *_tableView;
}
@property (nonatomic, strong) UITableView *tableView;

- (void)getInstalledApplist;
@end

//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class LSApplicationProxy;
@interface RPVApplication : NSObject
{
	LSApplicationProxy *_proxy;
}
@property(retain, nonatomic) LSApplicationProxy *proxy;

- (id)_provisioningProfileAtPath:(id)arg1;
- (id)locationOfApplicationOnFilesystem;
- (BOOL)hasEmbeddedMobileprovision;
- (id)applicationExpiryDate;
- (id)tvOSApplicationIcon;
- (id)applicationIcon;
- (id)applicationInstalledSize;
- (id)applicationVersion;
- (id)applicationName;
- (id)bundleIdentifier;
- (id)initWithApplicationProxy:(id)arg1;
@end